package hotel_check_in;

import java.awt.*;
import java.io.IOException;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class Panel_current_guests extends javax.swing.JPanel {

    private DefaultTableModel model;
    
    public Panel_current_guests() {
        setLayout(new GridLayout());;
        initComponents();
        try{
            ResultSet results = run();
            results(results);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        this.revalidate();
        
        this.add(jTable1);
    }

    public ResultSet run(){
        Database db = new Database();
    
        ResultSet results = db.get_from_database();
        return results;
    }
    
    private void results(ResultSet set) throws SQLException{
        while(set.next()){
            System.out.println("okay");
            String firstname = set.getString("firstname");
            String lastname = set.getString("lastname");
            String phone = set.getString("phone");
            String email = set.getString("email");
            String arrival_date = set.getString("arrival_date");
            String departure_date = set.getString("departure_date");
            String arrival_time = set.getString("arrival_time");
            String departure_time = set.getString("departure_time");
            String no_of_guests = set.getString("no_of_guests");
            String room_type = set.getString("room_type");
            String no_of_rooms = set.getString("no_of_rooms");
            String comments = set.getString("comments");
            
            Object[] row = {firstname, lastname, phone, email, arrival_date, departure_date, arrival_time, departure_time, no_of_guests, room_type, no_of_rooms, comments};
            model = (DefaultTableModel) jtable_results.getModel();
            model.addRow(row);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_results = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(java.awt.Color.white);

        jtable_results.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "Phone", "Email", "Arrival Date", "Departure Date", "Arrival Time", "Departure Time", "No. Of Guests", "Room Type", "No. Of Rooms", "Comments"
            }
        ));
        jScrollPane2.setViewportView(jtable_results);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtable_results;
    // End of variables declaration//GEN-END:variables
}
    
