package hotel_check_in;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.security.Timestamp;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.BoxLayout;
import javax.swing.JPanel;


public class Panel_new_guest extends javax.swing.JPanel {

    private String first_name;
    private String last_name;
    private String phone_number;
    private String email;
    private String date_arrival;
    private String date_departure;
    private String time_arrival;
    private String time_departure;
    private String no_of_guests;
    private String room_type;
    private String no_of_rooms;
    private String comments;
    
    public Panel_new_guest() {
        setLayout(new GridLayout());
        initComponents();
    }

    public void clear(){
        first_name = "";
        last_name = "";
        phone_number = "";
        email = "";
        date_arrival = "";
        date_departure = "";
        time_arrival = "";
        time_departure = "";
        no_of_guests = "";
        room_type = "";
        no_of_rooms = "";
        comments = "";

        jtextfield_first_name.setText("");
        jtext_field_last_name.setText("");
        jtext_field_phone_number.setText("");
        jtext_field_email.setText("");
        jtext_field_phone_number.setText("");
        jcombobox_arrival_time.setSelectedIndex(Integer.valueOf(0));
        jcombobox_departure_time.setSelectedIndex(Integer.valueOf(0));
        jtext_field_no_of_guests.setText("");
        jcombobox_room_type.setSelectedIndex(Integer.valueOf(0));
        jtext_field_no_of_rooms.setText("");
        jtextarea_comments.setText("");
    }
    
    public void add(){
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        first_name = jtextfield_first_name.getText();
        last_name = jtext_field_last_name.getText();
        phone_number = jtext_field_phone_number.getText();
        email = jtext_field_email.getText();
        date_arrival = format.format(jxcalender_arrival_date.getDate());
        date_departure = format.format(jxcalender_departure_date.getDate());
        time_arrival = (String)jcombobox_arrival_time.getSelectedItem();
        time_departure = (String)jcombobox_departure_time.getSelectedItem();
        no_of_guests = jtext_field_no_of_guests.getText();
        room_type = (String)jcombobox_room_type.getSelectedItem();
        no_of_rooms = jtext_field_no_of_rooms.getText();
        comments = jtextarea_comments.getText();
        //add to database using database object
        Database db = new Database();
        db.add_to_database(first_name, last_name, phone_number, email, date_arrival, date_departure, time_arrival, time_departure, no_of_guests, room_type, no_of_rooms, comments);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        dateComponentFormatter2 = new org.jdatepicker.impl.DateComponentFormatter();
        jlabel_first_name = new javax.swing.JLabel();
        jtextfield_first_name = new javax.swing.JTextField();
        jlabel_last_name = new javax.swing.JLabel();
        jtext_field_last_name = new javax.swing.JTextField();
        jlabel_phone_number = new javax.swing.JLabel();
        jtext_field_phone_number = new javax.swing.JTextField();
        jlabel_email = new javax.swing.JLabel();
        jtext_field_email = new javax.swing.JTextField();
        jlabel_arrival_date = new javax.swing.JLabel();
        jlabel_departure_date = new javax.swing.JLabel();
        jlabel_arrival_time = new javax.swing.JLabel();
        jlabel_departure_time = new javax.swing.JLabel();
        jlabel_room_type = new javax.swing.JLabel();
        jtext_field_no_of_guests = new javax.swing.JTextField();
        jlabel_no_of_guests = new javax.swing.JLabel();
        jtext_field_no_of_rooms = new javax.swing.JTextField();
        jlabel_no_of_rooms = new javax.swing.JLabel();
        jcombobox_room_type = new javax.swing.JComboBox<>();
        jcombobox_arrival_time = new javax.swing.JComboBox<>();
        jcombobox_departure_time = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextarea_comments = new javax.swing.JTextArea();
        jlabel_comments = new javax.swing.JLabel();
        jxcalender_arrival_date = new org.jdesktop.swingx.JXDatePicker();
        jxcalender_departure_date = new org.jdesktop.swingx.JXDatePicker();

        setBackground(java.awt.Color.white);

        jlabel_first_name.setText("First Name");

        jlabel_last_name.setText("Last Name");

        jlabel_phone_number.setText("Phone Number");

        jlabel_email.setText("Email");

        jlabel_arrival_date.setText("Arrival Date");

        jlabel_departure_date.setText("Departure Date");

        jlabel_arrival_time.setText("Arrival Time");

        jlabel_departure_time.setText("Departure Time");

        jlabel_room_type.setText("Room Type");

        jlabel_no_of_guests.setText("No. Of Guests");

        jlabel_no_of_rooms.setText("No. Of Rooms");

        jcombobox_room_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Twin", "Twin Double" }));

        jcombobox_arrival_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:01 - 07:00", "07:01 - 14:00", "14:01 - 19:00", "19:01 - 00:00" }));

        jcombobox_departure_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:01 - 07:00", "07:01 - 14:00", "14:01 - 19:00", "19:01 - 00:00" }));
        jcombobox_departure_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobox_departure_timeActionPerformed(evt);
            }
        });

        jtextarea_comments.setColumns(20);
        jtextarea_comments.setRows(5);
        jScrollPane1.setViewportView(jtextarea_comments);

        jlabel_comments.setText("Comments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabel_no_of_rooms, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jlabel_comments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtext_field_no_of_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabel_arrival_time, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcombobox_arrival_time, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlabel_arrival_date, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabel_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jxcalender_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabel_departure_time, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcombobox_departure_time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel_no_of_guests, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtext_field_no_of_guests, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_room_type, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcombobox_room_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtextfield_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtext_field_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtext_field_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtext_field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jxcalender_arrival_date, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_first_name)
                    .addComponent(jtextfield_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_last_name)
                    .addComponent(jtext_field_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_phone_number)
                    .addComponent(jtext_field_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_email)
                    .addComponent(jtext_field_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel_arrival_date)
                        .addComponent(jlabel_departure_date)
                        .addComponent(jxcalender_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jxcalender_arrival_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel_arrival_time)
                        .addComponent(jlabel_departure_time)
                        .addComponent(jcombobox_departure_time, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcombobox_arrival_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_no_of_guests)
                    .addComponent(jtext_field_no_of_guests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_room_type)
                    .addComponent(jcombobox_room_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_no_of_rooms)
                    .addComponent(jtext_field_no_of_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_comments))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcombobox_departure_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobox_departure_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombobox_departure_timeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcombobox_arrival_time;
    private javax.swing.JComboBox<String> jcombobox_departure_time;
    private javax.swing.JComboBox<String> jcombobox_room_type;
    private javax.swing.JLabel jlabel_arrival_date;
    private javax.swing.JLabel jlabel_arrival_time;
    private javax.swing.JLabel jlabel_comments;
    private javax.swing.JLabel jlabel_departure_date;
    private javax.swing.JLabel jlabel_departure_time;
    private javax.swing.JLabel jlabel_email;
    private javax.swing.JLabel jlabel_first_name;
    private javax.swing.JLabel jlabel_last_name;
    private javax.swing.JLabel jlabel_no_of_guests;
    private javax.swing.JLabel jlabel_no_of_rooms;
    private javax.swing.JLabel jlabel_phone_number;
    private javax.swing.JLabel jlabel_room_type;
    private javax.swing.JTextField jtext_field_email;
    private javax.swing.JTextField jtext_field_last_name;
    private javax.swing.JTextField jtext_field_no_of_guests;
    private javax.swing.JTextField jtext_field_no_of_rooms;
    private javax.swing.JTextField jtext_field_phone_number;
    private javax.swing.JTextArea jtextarea_comments;
    private javax.swing.JTextField jtextfield_first_name;
    private org.jdesktop.swingx.JXDatePicker jxcalender_arrival_date;
    private org.jdesktop.swingx.JXDatePicker jxcalender_departure_date;
    // End of variables declaration//GEN-END:variables
}
